// config/admins.js
module.exports = {
  admins: [
   process.env.ADMIN_UID
  ]
};


// PROBABLY NOT THE BEST WAY TO DO THIS, BUT IT WORKS FOR NOW. IN THE FUTURE, MAYBE ADD A PROPER USER MANAGEMENT SYSTEM WITH ROLES AND PERMISSIONS.